# Generated by Django 5.1.15 on 2026-09-17 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('name', models.CharField(help_text='Name of the board (required, non-empty)', max_length=255)),
            ],
            options={
                'db_table': 'boards',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='board_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when entity was last updated')),
                ('title', models.CharField(help_text='Title of the task (required, non-empty)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional task description')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], db_index=True, default='TODO', help_text='Current task status (TODO, IN_PROGRESS, DONE)', max_length=20)),
                ('board', models.ForeignKey(help_text='Board container this task belongs to (R3, R4)', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='src.board')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['board', 'status'], name='idx_tasks_board_status'), models.Index(fields=['board', 'created_at'], name='idx_tasks_board_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='task_title_not_empty'), models.CheckConstraint(condition=models.Q(('status__in', ['TODO', 'IN_PROGRESS', 'DONE'])), name='task_status_valid')],
            },
        ),
    ]
